chore(android): put back manifest rejection on permissions calls
ionic-team/capacitor pull request #3781
Opened 2020-11-09 16:12 UTC by carlpoole

This would need to be also handled when overriding `onRequestPermissionsResult` in a plugin.

2020-11-11 18:08 UTC, jcesarmobile requested changes
Requested a few changes.

`checkPermissions` doesn't reject if the permissions are not there, but since it's a new method I'm ok with it. It will return prompt, so the user will try to request the permissions and then get the rejection on the code that request the permissions.

2020-11-11 18:08 UTC, jcesarmobile commented on android/capacitor/src/main/java/com/getcapacitor/Plugin.java
> +            savedLastCall = null;
```suggestion
```

don't set the call to null, let the code after the removed do it.

2020-11-12 04:41 UTC, carlpoole commented on android/capacitor/src/main/java/com/getcapacitor/Plugin.java
> +        }
thanks, this is a lot cleaner. I applied your suggestion

2020-11-12 13:17 UTC, jcesarmobile approved these changes

2020-11-12 20:39 UTC, dwieeb commented
> This would need to be also handled when overriding `onRequestPermissionsResult` in a plugin.

Why might a plugin need to do this?

2020-11-12 20:43 UTC, carlpoole commented
> > This would need to be also handled when overriding `onRequestPermissionsResult` in a plugin.
> 
> Why might a plugin need to do this?

if its not handled when overriding, then the manifest check/rejection won't occur. Plugin authors can call `validatePermissions` to handle saving the plugin states and check if the manifest lacks the permissions in one go.

2020-11-12 20:50 UTC, dwieeb approved these changes

2020-11-12 20:50 UTC, merged