View controller
ionic-team/capacitor pull request #3973
Opened 2020-12-21 13:40 UTC by ikeith

_Description pending_

2020-12-22 13:12 UTC, jcesarmobile requested changes
Can we instead of having the `webViewClass` thing have an open method where the WebView is created so they can override that instead?
That way if their custom `WKWebView` subclass has a custom init they can use it, with current implementation it's not possible.

2020-12-23 18:17 UTC, jcesarmobile approved these changes

2020-12-23 19:52 UTC, dwieeb approved these changes

2020-12-23 19:52 UTC, merged

2024-06-27 14:39 UTC, tossaro commented
hello everyone, first of all thanks for opening CAPBridgeViewController so we can create subclasses, but I am facing blockers when adding hooks to web view lifecycle like didFinish, didFail etc, due to existing loadView is final function that have:
`let delegateHandler = WebViewDelegationHandler()`
I have created a subclass of WebViewDelegationHandler then use at capacitorDidLoad(), but it makes the bridge not work.
So could you please make loadView not final function? or maybe any additional open function that refer to delegation like instanceDescriptor function. thank you

existing capacitor 6.1.0 file CAPBridgeViewController:
`override public final func loadView() {
        // load the configuration and set the logging flag
        let configDescriptor = instanceDescriptor()
        let configuration = InstanceConfiguration(with: configDescriptor, isDebug: CapacitorBridge.isDevEnvironment)
        CAPLog.enableLogging = configuration.loggingEnabled
        logWarnings(for: configDescriptor)

        setStatusBarDefaults()
        setScreenOrientationDefaults()

        // get the web view
        let assetHandler = WebViewAssetHandler(router: router())
        assetHandler.setAssetPath(configuration.appLocation.path)
        assetHandler.setServerUrl(configuration.serverURL)
        let delegationHandler = WebViewDelegationHandler()
        prepareWebView(with: configuration, assetHandler: assetHandler, delegationHandler: delegationHandler)
        view = webView
        // create the bridge
        capacitorBridge = CapacitorBridge(with: configuration,
                                          delegate: self,
                                          cordovaConfiguration: configDescriptor.cordovaConfiguration,
                                          assetHandler: assetHandler,
                                          delegationHandler: delegationHandler)
        capacitorDidLoad()

        if configDescriptor.instanceType == .fixed {
            updateBinaryVersion()
        }
    }`