feat(android): ability to add page load listeners to the Capacitor WebView
ionic-team/capacitor pull request #4405
Opened 2021-03-29 18:43 UTC by carlpoole

Adds the ability to register a callback to execute when the WebView in Capacitor is finished loading.

Usage example: masking the view and fading it out when the web app is loaded, to hide ugly gaps in app loading

```
addPageLoadedListener((webView) -> fadeView.animate()
            .alpha(0f)
            .setDuration(duration)
            .setListener(new AnimatorListenerAdapter() {
                @Override
                public void onAnimationEnd(Animator animation) {
                    fadeView.setVisibility(View.GONE);
                }
            }));
```

2021-03-30 04:20 UTC, thomasvidas approved these changes

2021-04-02 14:16 UTC, thomasvidas approved these changes

2021-04-05 15:22 UTC, jcesarmobile requested changes
This implementation only allows to add listeners from the bridge builder. I think it should allow to add (and maybe remove) listeners after the bridge has been created too, so, in example, a plugin or some custom user code in the activity class can add new listeners

2021-04-08 10:43 UTC, jcesarmobile approved these changes
looks good

2021-04-08 14:04 UTC, merged