feat(ios): Add new iOS15 media capture permission delegate
ionic-team/capacitor pull request #5196
Opened 2021-11-02 08:50 UTC by samydoesit

Delegates media capture permissions to the app and remembers the user's decision for iOS15.

[https://developer.apple.com/documentation/webkit/wkuidelegate/3763087-webview#discussion](https://developer.apple.com/documentation/webkit/wkuidelegate/3763087-webview#discussion)

Thanks and credits to @7freaks-otte who found the solution. :)
[https://forum.ionicframework.com/t/prevent-for-reprompting-webrtc-webview-permissions-ios15/215240/2?u=samydoesit](https://forum.ionicframework.com/t/prevent-for-reprompting-webrtc-webview-permissions-ios15/215240/2?u=samydoesit)

2021-11-03 08:46 UTC, samydoesit commented
Looks like that the CI should use latest Xcode13 on macos-11. https://github.com/actions/virtual-environments/issues/4060

2021-11-22 13:40 UTC, jcesarmobile requested changes
Hello.
Thanks for the PR!

Since we still need to support Xcode 12 and the method is not available there, the function needs to be wrapped inside a `#if compiler(>=5.5)` as proposed since that's the swift version shipped on Xcode 13, so that code won't run on Xcode 12 but the build won't fail as it does now.

2021-11-22 13:40 UTC, jcesarmobile commented on ios/Capacitor/Capacitor/WebViewDelegationHandler.swift
> +    // This delegates media capture permission requests to the app and also remembers the user’s decision.
```suggestion
    // TODO: remove once Xcode 12 support is dropped
    #if compiler(>=5.5)
```

2021-11-22 13:40 UTC, jcesarmobile commented on ios/Capacitor/Capacitor/WebViewDelegationHandler.swift
> +    }
```suggestion
    }
    #endif
```

2021-11-22 17:07 UTC, jcesarmobile approved these changes
Thanks!
It looks good, we will merge once we start working on next minor release, might take a few weeks, but will be included.

2022-01-05 17:56 UTC, merged