chore: cap4 deployment automations
ionic-team/capacitor pull request #5636
Opened 2022-05-23 15:53 UTC by IT-MikeS

2022-05-24 14:24 UTC, giralte-ionic approved these changes

2022-05-24 14:34 UTC, theproducer approved these changes

2022-05-26 10:46 UTC, jcesarmobile requested changes
Added a minor comment.
Also I've realized we are missing the RC release, I think we should have that one too (there was a `release:rc` that has been removed). We need that because we do alpha, then beta and finally rc before the final is released.
I'm not sure about using the alpha/beta tags, at the moment we are using next tag for all alpha, beta and rc releases, I think a single tag for those would be better since we do them sequentially.

2022-05-26 10:46 UTC, jcesarmobile commented on .github/workflows/ci.yml
> +  # deploy-next:
delete instead of comment

2022-05-31 14:48 UTC, jcesarmobile approved these changes

2022-05-31 15:19 UTC, jcesarmobile approved these changes

2022-06-01 15:15 UTC, giralte-ionic approved these changes

2022-06-10 14:30 UTC, merged