chore: Update CONTRIBUTING.md
ionic-team/capacitor pull request #6286
Opened 2023-02-09 15:29 UTC by giralte-ionic

also removed the publishing instructions as I'm not sure why anyone but us would use it and our publishing docs are in [ionic's private] notion

2023-02-09 15:37 UTC, jcesarmobile requested changes
I think the publishing information is useful even if nobody other than us can publish, it's always good to have that information in the repo instead of having to navigate through notion to find it. Also the lerna part about using fixed versioning can help users see all packages are released at the same time with the same version number.

But the information is out of date since we now use github actions to publish.

2023-02-09 15:37 UTC, jcesarmobile commented on CONTRIBUTING.md
> +* [`3.x`](https://github.com/ionic-team/capacitor/tree/2.x): Capacitor 3 (bug and security fixes only)
we are not doing bug fixes, so not sure if it should say "security fixes only", or if we should be backporting bug fixes

2023-02-09 16:05 UTC, jcesarmobile approved these changes

2023-02-09 17:09 UTC, ItsChaceD requested changes

2023-02-09 17:09 UTC, ItsChaceD commented on CONTRIBUTING.md
> +* [`3.x`](https://github.com/ionic-team/capacitor/tree/2.x): Capacitor 3 (security fixes only)
The link should be `3.x`

2023-02-15 17:09 UTC, ItsChaceD approved these changes

2023-02-15 17:09 UTC, merged