feat(android): Removing jetifier
ionic-team/capacitor pull request #6333
Opened 2023-02-27 23:05 UTC by theproducer

Removes `android.enableJetifier` in core and in the publish script as its no longer needed for modern libraries.

2023-02-28 14:23 UTC, jcesarmobile requested changes
Can you please move the android-template/gradle.properties change to a separate PR?
We should make any android-template change a separate PR for easier tracking of what's required for the Capacitor 4 to 5 migration.

2023-03-01 10:47 UTC, jcesarmobile commented on android-template/gradle.properties
> +
```suggestion
```

2023-03-01 10:47 UTC, jcesarmobile approved these changes

2023-03-01 16:05 UTC, IT-MikeS approved these changes

2023-03-01 16:36 UTC, merged