chore(android): move package to build gradle
ionic-team/capacitor pull request #6379
Opened 2023-03-09 16:33 UTC by IT-MikeS

2023-03-09 16:49 UTC, jcesarmobile requested changes
can you remove the existing code for replacing the package name in the `AndroidManifest.xml`?
it's not needed since the package is being removed

2023-03-13 14:17 UTC, theproducer approved these changes

2023-03-13 15:34 UTC, jcesarmobile requested changes
Just noticed that we have the activity name hardcoded to `android:name="com.getcapacitor.myapp.MainActivity"`
Which no longer gets replaced because I told you to remove the code that writes in the `AndroidManifest.xml` 🙈 
but in new android apps the MainActivity is references as `.MainActivity` (without package).
So, can you change it to `android:name=".MainActivity"`?

2023-03-13 15:50 UTC, jcesarmobile approved these changes

2023-03-14 14:21 UTC, merged