feat(android): update gradle to 8.0.2 and gradle plugin to 8.0.0
ionic-team/capacitor pull request #6497
Opened 2023-04-12 15:55 UTC by IT-MikeS

Dev build for this PR is tagged as: 

~~`@capacitor/{core,cli,android,ios}@5.0.0-dev-20230412T155745.0`~~

~~`@capacitor/{core,cli,android,ios}@5.0.0-dev-20230414T153043.0`~~

`@capacitor/{core,cli,android,ios}@5.0.0-dev-20230414T155819.0`

2023-04-12 17:42 UTC, markemer commented
We'll have to make sure to update the migrate script if and when we go with this.

2023-04-14 14:48 UTC, jcesarmobile requested changes
you also need to update the wrapper files by running `./gradlew wrapper --distribution-type all --gradle-version 8.0.2 --warning-mode all`, but in the android-template it can by tricky since it's missing files

2023-04-14 15:02 UTC, markemer commented
We'll also need to either update the migrate script here or in another PR.

2023-04-14 16:11 UTC, jcesarmobile commented on .github/workflows/ci.yml
> +      - name: set up JDK 11
```suggestion
      - name: set up JDK 17
```

2023-04-14 16:32 UTC, markemer commented
> Yeah, this pr is only for the template, we need another one updating capacitor android and another updating the migrate command, and the plugins too

Not to be that guy asking for homework, but should we add subtasks or a bunch of tickets for this stuff?

2023-04-14 16:46 UTC, jcesarmobile approved these changes

2023-04-17 14:20 UTC, markemer approved these changes

2023-04-17 15:41 UTC, merged