chore: update lerna and fix full-publish
ionic-team/capacitor pull request #6731
Opened 2023-07-13 16:26 UTC by IT-MikeS

2023-07-13 16:29 UTC, jcesarmobile approved these changes
the full publish fix looks ok
the lerna update no idea, hope it works 🤞

2023-07-13 16:30 UTC, jcesarmobile requested changes
oh, wait, this is Capacitor repo, I think we want to keep releasing all packages together, the independent releases should be for plugins only

2023-07-13 17:00 UTC, IT-MikeS commented
Didn't mean to delete the force-publish here, meant to just move it for readability. Restored it.

2023-07-13 17:09 UTC, jcesarmobile approved these changes

2023-07-14 15:13 UTC, giralte-ionic approved these changes

2023-07-14 17:23 UTC, markemer approved these changes

2023-07-25 16:27 UTC, merged