fix: stop crashing from `objc_getClassList`
ionic-team/capacitor pull request #7187
Opened 2024-01-12 16:37 UTC by markemer

2024-01-12 16:41 UTC, giralte-ionic requested changes
please also run a fat

2024-01-12 16:41 UTC, giralte-ionic commented on ios/Capacitor/Capacitor/CapacitorBridge.swift
> +#warning("remove this before merging! To test for crash")
I'm guessing you wanted to remove this?

2024-01-12 17:14 UTC, Steven0351 commented on ios/Capacitor/Capacitor/CapacitorBridge.swift
> +            if let capPlugin = plugin as? CapacitorPlugin.Type {
We still need to keep this check
```swift
if plugin is CAPInstancePlugin.Type { continue }
```

2024-01-12 17:37 UTC, markemer commented on ios/Capacitor/Capacitor/CapacitorBridge.swift
> +#warning("remove this before merging! To test for crash")
Pulled it before I forget for real.

2024-01-12 19:51 UTC, giralte-ionic approved these changes

2024-01-15 20:43 UTC, Steven0351 commented on ios/Capacitor/Capacitor/CapacitorBridge.swift
> -            [CAPHttpPlugin.self, CAPConsolePlugin.self, CAPWebViewPlugin.self, CAPCookiesPlugin.self]
It looks like we may not be registering the core plugins after this block has been removed.

2024-01-15 21:02 UTC, theproducer approved these changes

2024-01-15 21:32 UTC, Steven0351 approved these changes

2024-01-15 22:13 UTC, merged