fix(spm): add product lines to Package.swift
ionic-team/capacitor pull request #7278
Opened 2024-02-22 19:58 UTC by markemer

Currently in draft as this fixes one problem but is dependent on the following

- [ ] Changing the SPM Repo name
- [ ] Fixing the Names in all the Package.swift files in @ionic-team/capacitor-plugins
- [ ] Fixing the iOS Template

2024-02-27 11:13 UTC, giralte-ionic approved these changes

2024-02-28 13:49 UTC, jcesarmobile requested changes
This fails to detect deleted plugins, they are kept in the `Package.swift` file, making the app fail.

I think we should go with full file generation (or at least everything after the `// DO NOT MODIFY THIS FILE`) instead of appending the plugins to the existing ones, this way it will generate the file without the uninstalled plugins, otherwise we would need to keep track of installed plugins on every sync and compare with the previous list and update the list, etc.

2024-02-28 14:27 UTC, jcesarmobile commented
another idea is to keep the file as is and append the dependencies to the end, I've tried this and it works:

```
package.dependencies.append(.package(name: "CapacitorActionSheet", path: "../capacitor-plugins/action-sheet"))

package.targets.first?.dependencies.append(.product(name: "CapacitorActionSheet", package: "CapacitorActionSheet"))
```

2024-02-29 16:21 UTC, markemer commented
Thanks for the bug callout - generating the whole thing from the start might be the answer, or something programmatic.

2024-02-29 22:28 UTC, Steven0351 commented on cli/src/util/spm.ts
> +export async function checkPackageManager(config: Config): Promise<string> {
Maybe make this return a `Promise<'SPM' | 'Cocoapods'>` instead of `string`

2024-03-04 17:16 UTC, jcesarmobile requested changes
just a few formatting issues on the resulting file

2024-03-04 17:16 UTC, jcesarmobile commented on cli/src/util/spm.ts
> +            .package(url: "https://github.com/ionic-team/capacitor-spm.git", branch: "main")`;
```suggestion
  let packageSwiftText = `// swift-tools-version: 5.9
import PackageDescription

// DO NOT MODIFY THIS FILE - managed by Capacitor CLI commands
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "CapApp-SPM",
            targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-spm.git", branch: "main")`;
```

2024-03-04 17:16 UTC, jcesarmobile commented on cli/src/util/spm.ts
> +    packageSwiftText += `,\n            .package(name: "${plugin.ios?.name}", path: "${relPath}")`;
```suggestion
    packageSwiftText += `,\n        .package(name: "${plugin.ios?.name}", path: "${relPath}")`;
```

2024-03-04 17:16 UTC, jcesarmobile commented on cli/src/util/spm.ts
> +                    .product(name: "Cordova", package: "capacitor-spm")`;
```suggestion
    ],
    targets: [
        .target(
            name: "CapApp-SPM",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-spm"),
                .product(name: "Cordova", package: "capacitor-spm")`;
```

2024-03-04 17:16 UTC, jcesarmobile commented on cli/src/util/spm.ts
> +    packageSwiftText += `,\n                    .product(name: "${plugin.ios?.name}", package: "${plugin.ios?.name}")`;
```suggestion
    packageSwiftText += `,\n                .product(name: "${plugin.ios?.name}", package: "${plugin.ios?.name}")`;
```

2024-03-04 17:16 UTC, jcesarmobile commented on cli/src/util/spm.ts
> +`;
```suggestion
            ]
        )
    ]
)
`;
```

2024-03-07 15:43 UTC, merged