feat(cli): Support bun when running cap migrate
ionic-team/capacitor pull request #7386
Opened 2024-04-05 19:17 UTC by dtarnawsky

Adds support for bun when running:
`cap migrate --noprompt --packagemanager=bun`

Resolves #7326

2024-04-05 19:36 UTC, giralte-ionic approved these changes

2024-04-09 14:11 UTC, jcesarmobile requested changes

2024-04-09 14:11 UTC, jcesarmobile commented on cli/src/tasks/migrate.ts
> +          return getCommandOutput(runCommand, ['cap', 'sync']);
I don't think this needs to be changed, we require node to be installed, so `npx` will always be available, I don't think there is any advantage on using `bunx` over `npx` in this case as it't used for running the already installed `@capacitor/cli` package, not for running a package that is not installed yet (in this case there would be a difference).

If we do this for bun, then we should do the same for the other package managers as they also have `npx` alternatives, but I don't think it should be done for any of them.

2024-04-10 13:57 UTC, jcesarmobile approved these changes

2024-04-10 14:01 UTC, merged