feat(cli)!: change telemetry from opt-in to opt-out
ionic-team/capacitor pull request #7714
Opened 2024-10-11 20:14 UTC by eric-horodyski

Modify telemetry such that is it opt-out instead of the current opt-in behavior:

- Telemetry checks only occur on specified commands (`init`, `sync`, `copy`, `update`, etc.) per the existing source.
- If the user has not yet opted in-or-out: 
  - The user will be automatically opted-in.
  - The user will be printed out a thank you message with instructions on how to opt-out (if they wish).
- Once the user has made a preference one way or the other, they will not see any telemetry messaging.
- Users with existing telemetry preferences will have them preserved.

2024-10-14 19:19 UTC, markemer approved these changes

2024-10-15 11:17 UTC, jcesarmobile requested changes
why change the `output.write` to `logger.msg`. I don't see any visible differences between them, but on `cli/src/tasks/telemetry.ts` the `THANK_YOU` message is also written still with `output.write`, so for consistency I would keep `output.write` for both.

The `THANK_YOU` message needs more rewording as it says "you can change your mind", but that made sense when the user was prompted, now it isn't their decision, so should  say something like "You can disable telemetry at any time", and provide the whole command to disable it `npx cap telemetry off`.

Also, we should update the telemetry docs for Capacitor 7, can you create a ticket for tracking it? 
We don't have Capacitor 7 alpha docs yet, but I have asked Jared to create them.

2024-10-15 13:55 UTC, eric-horodyski commented
> why change the `output.write` to `logger.msg`. I don't see any visible differences between them, but on `cli/src/tasks/telemetry.ts` the `THANK_YOU` message is also written still with `output.write`, so for consistency I would keep `output.write` for both.

For some reason, `output.write` caps at writing 2 lines of text so I had to use `logger.msg`.

2024-10-15 15:57 UTC, eric-horodyski commented
Two changes have been added:

1. Use `output.write()` to write out the message when the user is opted-in.
2. Retain the original messaging (from when telemetry was opt-out) to be written out when the user manually turns telemetry on.

2024-10-15 17:12 UTC, jcesarmobile commented on cli/src/telemetry.ts
> +  `\nYou can disable telemetry at any time by using the ${c.input('npx cap telemetry')} command.`;
```suggestion
  `\nYou can disable telemetry at any time by using the ${c.input('npx cap telemetry off')} command.`;
```

2024-10-15 19:28 UTC, markemer approved these changes
Other than Julio's change, this works.

2024-10-18 17:49 UTC, merged